# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_item',
            field=models.ManyToManyField(related_name='user_item', to='item_app.Item'),
        ),
    ]
